### ISSUE TITLE
Непросмотренные - ошибка

### ISSUE THREAD

**Issue by shtricul** [fantomnotabene/NB-series-player#1]
Спасибо за workflow - отличная вещь, вот только есть такая ошибка:
![2016-07-12 17 41 54](https://cloud.githubusercontent.com/assets/721883/16771176/965891b2-4860-11e6-9538-72e859d8395d.png)
Если связано с плеером - выбрал QuickTime

**Comment by fantomnotabene** [comment]
С плеером не связано. Связано со списком Ваших непросмотренных на myshows.
Если не сложно, перейдите в браузере (предварительно авторизовавшись в нем на myshows) по адресу http://api.myshows.ru/profile/episodes/unwatched/ и пришлите ответ сервера. Полагаю, там будет [].
Не предусмотрел, видимо, пустой список непросмотренных.
Остальное работает?

**Comment by fantomnotabene** [comment]
Выпустил версию 1.1
При запуске "сериалы" из workflow, происходит проверка на существование обновления.
Можно обновиться таким методом или перекачать файл воркфлоу.
Отпишитесь, ушла ли проблема

**Comment by shtricul** [comment]
Благодарю за быструю реакцию! Проблема решена, все работает отлично!

**Comment by fantomnotabene** [comment]
Не лучший вариант - привязывать этот workflow к сериалокачалке, которую ставить будут далеко не все пользователи workflow. Можно попробовать реализовать самодостаточный загрузчик в составе workflow. Впрочем, когда в списке непросмотренных выбираешь пункт, открывается страница эпизода и там есть ссылки на всевозможные сайты студий озвучания. Так что это позволит сохранить лишь пару кликов мышкой, удобство чего, впрочем, недооценить невозможно. Подумаю над реализацией.
Вопрос закрываю, раз проблема решена
